## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [30]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [28]:
import numpy as np
import pandas as pd

In [47]:
# Type your solution here
# Q1-1
df = pd.DataFrame(data)
print(df)

#Q1-2
df.loc[(df.job == "psychologist") & (df.num_cars > df.family_size) | (df.job == "teacher") & (df.num_cars > df.family_size), :]

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [48]:
#Q1-3: Select people who have at most 2 family members and at least 1 car.
df.loc[(df.family_size <= 2) & (df.num_cars > 0)]

name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

In [41]:
#Q1-4: Write a code that get number of unique jobs in this dataset.
unique_jobs = df['job'].unique()
num_of_unique_jobs = len(unique_jobs)
print(num_of_unique_jobs)

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [49]:
# import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
# Type your solution here
#print(fruit.to_list())
#print(weights.to_list())
weights.groupby(fruit).mean()

apple     6.00
banana    4.75
carrot    6.00
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [2]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [59]:
# Type your solution here
#Q3-1: Write a NumPy program to get the indices of the sorted elements of course_name array.
course_copy = course_name.copy()
course_copy.sort()
for i in course_name:
  print(i + ": " + str(np.where(course_copy == i)))

# Q3-2: Write numpy code to check whether each element of course_name array starts with "P".
starts_with_p = np.char.startswith(course_name,"P")
print(starts_with_p)

Python: (array([2]),)
JS: (array([0]),)
examples: (array([3]),)
PHP: (array([1]),)
html: (array([4]),)
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [4]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [22]:
# Type your solution here
# Q4-1: Reverse the student_id array. Print both original and reversed array.
reversed_array = np.flipud(student_id)
print(student_id)
print(reversed_array)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [23]:
# Type your solution here
# Q4-2: Get the 3-largest values of student_id array.
sorted_array = np.sort(student_id)
print(sorted_array[4:])

[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [24]:
# Type your solution here

# Hint: you can use arange to start off (returns an ndarray)
mults_of_three = np.arange(3,100,3,dtype=None).sum()
mults_of_five = np.arange(5,100,5,dtype=None).sum()
mults_of_fifteen = np.arange(15,100,15, dtype=None).sum()
#print(mults_of_three)
#print(mults_of_five)
#print(mults_of_fifteen)
print(mults_of_three + mults_of_five - mults_of_fifteen)


2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [25]:
import numpy as np
# original array
arr = np.arange(12).reshape(3,4)
print(arr)
# Q6.1. Write a code to swap column 1 with column 2.
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [26]:
# Type your solution here
# original array
arr = np.arange(12).reshape(3,4)
print(arr)
# Q6.2. Write a code to swap row 0 with row 1.
arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
